<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jonathan Lieb">

<title>Analysis and Prediction of MSHSAA Girls Basketball Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Analysis_files/libs/quarto-html/quarto.js"></script>
<script src="Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Analysis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Analysis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#project-design" id="toc-project-design" class="nav-link active" data-scroll-target="#project-design">Project Design</a>
  <ul class="collapse">
  <li><a href="#project-overview" id="toc-project-overview" class="nav-link" data-scroll-target="#project-overview">Project Overview</a></li>
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a></li>
  <li><a href="#steps-of-the-analysis" id="toc-steps-of-the-analysis" class="nav-link" data-scroll-target="#steps-of-the-analysis">Steps of the Analysis</a></li>
  <li><a href="#primary-challenges-faced" id="toc-primary-challenges-faced" class="nav-link" data-scroll-target="#primary-challenges-faced">Primary Challenges Faced</a></li>
  <li><a href="#modeling-goals" id="toc-modeling-goals" class="nav-link" data-scroll-target="#modeling-goals">Modeling Goals</a></li>
  </ul></li>
  <li><a href="#project-workflow" id="toc-project-workflow" class="nav-link" data-scroll-target="#project-workflow">Project Workflow</a>
  <ul class="collapse">
  <li><a href="#steps-of-the-analysis-1" id="toc-steps-of-the-analysis-1" class="nav-link" data-scroll-target="#steps-of-the-analysis-1">Steps of the Analysis</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#practical-recommendations" id="toc-practical-recommendations" class="nav-link" data-scroll-target="#practical-recommendations">Practical Recommendations</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#changes-for-future-work" id="toc-changes-for-future-work" class="nav-link" data-scroll-target="#changes-for-future-work">Changes for Future Work</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis and Prediction of MSHSAA Girls Basketball Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jonathan Lieb </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="project-design" class="level1">
<h1>Project Design</h1>
<section id="project-overview" class="level2">
<h2 class="anchored" data-anchor-id="project-overview">Project Overview</h2>
<p>High school athletics are a major part of the culture in the United States, however it is a field largely untouched by data and analytics. Not only is information regarding high school sports sometimes difficult to find, but it is often heavily disorganized and messy. One of the most difficult things to measure in high school sports is how good a team is relative to other teams. This is even difficult within a single sport in a single state. Each state has hundreds of teams, often spanning multiple classes, sometimes separated by leagues (private and public), and generally distanced by geography. Occasionally, states will have coaches rank the top ten teams, but this is almost entirely subjective, driven heavily by the opinions and bias of the coaches who vote, and fails to measure any other teams not in the top 10. Our questions going into this analysis and project revolve around addressing these issues by focusing on a couple of key questions:</p>
<ol type="1">
<li><p>Can historical data for a single high sport in a single state be accumulated into a single dataset that is easily accessible and usable?</p></li>
<li><p>Can we predict an outcomes, both scores and win probabilities, of every single game played with a data driven model that is accurate enough to be useful?</p></li>
<li><p>Can we rank every team in the state, rather than just the top 10 with analytics rather than opinion?</p></li>
<li><p>Can we determine what factors are most important in determining the outcome of a high school game?</p></li>
<li><p>Can this information be processed and presented in a way that is easily accessible and interpretable to the public, while being adaptable to new data?</p></li>
</ol>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>To address these questions, we will focus on the Missouri State High School Activities Association (MSHSAA) women’s basketball data. The data for this project will be scraped from the MSHSAA women’s basketball scoreboard, which has game scores going back approximately 15 years. This data will be aggregated into a single dataset that can then be cleaned, processed, transformed, and analyzed. The data will include information on the teams, scores, locations, dates, and classes of the teams involved. The plethora of easily accessible game data makes this a perfect candidate for analysis, and the field of women’s high school basketball in Missouri is almost entirely unexplored.</p>
</section>
<section id="steps-of-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="steps-of-the-analysis">Steps of the Analysis</h2>
<ol type="1">
<li><strong>Scrape the data</strong>: Use the <code>rvest</code> package to scrape the data from the MSHSAA website and put it in a data frame.</li>
<li><strong>Clean the data</strong>: Use the <code>dplyr</code> package to clean the data, including removing unnecessary columns and rows, and converting data types. This also involves finding errors in the data and replacing them with the most accurate data.</li>
<li><strong>Create a modeling dataset</strong>: Use the <code>dplyr</code> package to create a modeling dataset that includes relevant features for analysis and prediction. This includes creating new features based on existing data, such prior team scoring metrics, strength of schedule metrics, and strength of record metrics.</li>
<li><strong>Perform EDA</strong>: Use the <code>ggplot2</code> package to perform exploratory data analysis (EDA) on the modeling dataset. This includes creating visualizations to understand the distribution of features, relationships between features, and any potential patterns in the data.</li>
<li><strong>Build a predictive model</strong>: Use the <code>tidymodels</code> package to build a predictive model using the modeling dataset. This includes splitting the data into training and testing sets, selecting relevant features, and training the model using various algorithms (e.g., linear regression, decision trees, etc.).</li>
<li><strong>Evaluate the models</strong>: Use the <code>yardstick</code> package to evaluate the performance of the predictive model using various metrics. For the point estimation, this includes metrics such as RMSE, MAE, and R-squared. For the classification model, this includes metrics such as brier score, log loss, and accuracy.</li>
<li><strong>Interpret the importance of variables</strong>: Coefficients or importance scores from the model will be used to interpret the importance of different variables in predicting the outcome of games. This includes understanding which features are most influential in determining the score and how they interact with each other.</li>
<li><strong>Make predictions</strong>: Use the trained model to make predictions on new data. This includes using the model to predict the outcome of future games and evaluating the accuracy of those predictions.</li>
<li><strong>Create a Shiny app</strong>: Use the <code>shiny</code> package to create a Shiny app that allows users to interact with the model and make predictions. It will also include team rankings that are a measure of projected performance against teams in the same class based on the model.</li>
<li><strong>Make the Process Automated</strong>: Adjust the scraping, cleaning, modeling data creation, and prediction processes to be automated. This includes creating a function that can be run on a schedule to update the data and predictions automatically each night.</li>
</ol>
</section>
<section id="primary-challenges-faced" class="level2">
<h2 class="anchored" data-anchor-id="primary-challenges-faced">Primary Challenges Faced</h2>
<ol type="1">
<li><strong>Data Cleaning</strong>: The data scraped from the MSHSAA website was not in a clean format, and contained plentiful errors. This means that not only will I have to scrape the scoreboard page, but when certain conflicts arise scrape the relevant team pages and automate the decision process on which data to use.</li>
<li><strong>Lack of Data to Start the Season</strong>: The data at the start of the season is limited and makes prediction difficult. This means that I will have to find some way to estimate the effect of prior years data as well as current data and league average data to make predictions that are not completely random.</li>
<li><strong>Correlation between Predictors</strong>: A handful of the predictors in the modeling dataset are correlated with each other, which can lead to multicollinearity issues in the predictive model. This means that I will have to be careful in selecting the features to include in the model and may need to use techniques such as regularization to mitigate this issue.</li>
<li><strong>Automation</strong>: Automating the scraping, cleaning, modeling data creation, and prediction processes is a complex task that requires careful planning and testing, which sometimes fails based on internet connection and the MSHSAA website. This means that I will have to create a robust system that can handle errors and exceptions, and ensure that the data is updated regularly.</li>
</ol>
</section>
<section id="modeling-goals" class="level2">
<h2 class="anchored" data-anchor-id="modeling-goals">Modeling Goals</h2>
<section id="point-estimation" class="level8">
<p class="heading">Point Estimation</p>
<ol type="1">
<li>RMSE less than 10 points</li>
<li>MAE less than 7.5 points</li>
</ol>
</section>
<section id="classification" class="level8">
<p class="heading">Classification</p>
<ol type="1">
<li>Brier score less than 0.15</li>
<li>Accuracy greater than 0.80</li>
</ol>
</section>
</section>
</section>
<section id="project-workflow" class="level1">
<h1>Project Workflow</h1>
<section id="steps-of-the-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="steps-of-the-analysis-1">Steps of the Analysis</h2>
<ol type="1">
<li><strong>Scrape the data</strong>: The data was successfully scraped from the MSHSAA girl’s scoreboard using the <code>initial_scrape.R</code> script, which uses the functions from <code>Functions/webscrape_new_games.R</code>. The original data consisted of 203,272 rows and 20 columns related to the teams and identifying traits about them, score, location, and date. The data contains two rows for every game that was played. One from each teams perspective. The data is stored at <code>Data/initial_data.parquet</code>. This data consists of every game played from November 1, 2010 to January 27, 2025. The head of the data is shown below</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 20
  school         score class_and_district   class district opp         opp_score
  &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt;
1 Miami (Amoret)    11 Class 1 District 7&nbsp;      1        7 Archie             70
2 Versailles        37 Class 3 District 10&nbsp;     3       10 Eugene             70
3 South Holt        53 Class 1 District 14&nbsp;     1       14 Fairfax            43
4 Van Buren         30 Class 2 District 2&nbsp;      2        2 Thayer             34
5 Archie            70 Class 2 District 13&nbsp;     2       13 Miami (Amo…        11
6 Eugene            70 Class 3 District 10&nbsp;     3       10 Versailles         37
# ℹ 13 more variables: opp_class_and_district &lt;chr&gt;, opp_class &lt;dbl&gt;,
#   opp_district &lt;dbl&gt;, result &lt;chr&gt;, tourney &lt;chr&gt;, location &lt;chr&gt;,
#   date &lt;date&gt;, schoolid &lt;dbl&gt;, opp_schoolid &lt;dbl&gt;, game_id &lt;chr&gt;,
#   season &lt;dbl&gt;, w_l &lt;fct&gt;, h_a_n &lt;fct&gt;</code></pre>
</div>
</div>
<ol start="2" type="1">
<li><strong>Clean the data</strong>: The data was cleaned in the <code>initial_scrape.R</code> script as well, calling functions from <code>Functions/clean_errors.R</code> and by association <code>Functions/add_home_away.R</code>, <code>Functions/clean_add_reverse_row.R</code>, and <code>Functions/scrape_team_page.R</code>. There were 8 major types of errors in the data. These were:<br>
</li>
</ol>
<ul>
<li>Same score between teams within one week of each other<br>
</li>
<li>Almost same score between two teams within 3 days of each other (scores within 5)<br>
</li>
<li>One teams score basically nothing (score for one less than 5)<br>
</li>
<li>Flipped scores (One score in day or within 3 days has one team winning and the the other has the other team winning with the same score)<br>
</li>
<li>Two different scores in the same day<br>
</li>
<li>Score for one of the teams is equal to their schoolid.<br>
</li>
<li>The School or opponent is “TBD”<br>
Each of these required unique solutions to fix, which often involved scraping team pages to see if the score was listed there. The data was then saved to <code>Data/cleaned.parquet</code>. This cleaned data consists of 196,792 rows and 20 columns.</li>
</ul>
<ol start="3" type="1">
<li><p><strong>Create a modeling dataset</strong>: The modeling dataset was created in the <code>initial_scrape.R</code> script as well, calling functions from <code>Functions/create_modeling_data.R</code>. This involved creating new features based on existing data, such as prior team scoring metrics, strength of schedule metrics, strength of record metrics, and historical versions of each of the metrics. Each metric only includes prior information about the team, meaning no future or current game data is leaked into the predictors. The modeling dataset was saved to <code>Data/modeling_data.parquet</code>. The modeling dataset consists of 196,792 rows and 70 columns. Please check out the <code>modeling_data_glossary.R</code> script for a full description of the features.</p></li>
<li><p><strong>Perform EDA</strong>: The EDA was performed in the <code>EDA.R</code> script, which includes visualizations to understand the distribution of features, relationships between features, and any potential patterns in the data. The scores themselves for the girls games are normally distributed, with a mean of 45 and standard deviation of 15. A plot of the scores can be seen below.</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The primary issue with the data is the large amount of missing values in the modeling data, which occur for the first game for all of the teams. Many of the variables are also relatively normally distributed until you impute values for missing data, which makes more leptokurtic distributions. Correlations between variables and the target variable were also examined, as well as correlations between pairs of variables. It was found that a teams own statistical measures were more closely related to performance than the opponents statistical measures. The most highly correlated variables with the score of game for a team were all variables that measure a teams offensive scoring ability.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Correlation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prior PTS Per Game</td>
<td>0.576</td>
</tr>
<tr class="even">
<td>Offensive Weighted Efficiency</td>
<td>0.554</td>
</tr>
<tr class="odd">
<td>Offensive Efficiency Rate</td>
<td>0.552</td>
</tr>
</tbody>
</table>
<p>Offensive weighted efficiency attempts to measure offensive performance compared to the amount of points allowed per game that the opponent averages. Offensive efficiency rate attempts to measure the offensive performance of a team on an estimated possession basis. Obviously these were all highly correlated with each other as well. Since the data for each game is essentially duplicated, opponents prior points per game is the most highly correlated with the opponents score and so on. Please look at the <code>EDA.R</code> script for more details on the exploratory data analysis.</p>
<ol start="5" type="1">
<li><strong>Build a predictive model</strong>: It was decided very quickly to only use data from 2015 on for building a model. This was done because all prior season values for 2011 are NA. Additionally, approximately half of all games from 2012 are not reported. By 2013 it appeared most games were being properly recorded. In order to allow an extra buffer year after this and because we would still have 10 years worth of data for training and testing it was decided to use the 2014-2015 season as the earliest data for the model.</li>
</ol>
<p>Model code for a variety of different model structures has been stored in <code>Model_Code/</code>. Original models were fit for a variety of models and the original results can be seen in the plot below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots/reg_all_once_rmse.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots/reg_all_once_mae.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
<p>The models include linear regression models, boosted trees, neural networks, mixed effects models, penalized regression, and more. Modeling was done using the <code>tidymodels</code> package. Data was split into training and testing sets each time with a 60/40 split. The same seed was used for each model. Most used tuning with resamples and cross validation and then tuning with <code>tune_bayes()</code> to find the best hyperparameters.</p>
<p>After careful consideration regarding the predictive power of different models compared to their interpretability, reusablity, and ease of use, it was decided to use a simple linear regression model for predicting score and opponent’s score and a logistic regression model for predicting the outcome (win or loss) of the game. The reasoning for this was rooted largely in practical reasons. The simple models were not getting significantly outperformed by more complex models, yet provided ease of use and interpretability. Coefficients for linear regression can be easily interpreted, as can the odds ratios for logistic regression. Additionally these models allowed for reciprocal, or symmetric predictions, meaning that the model would effective predict the same score for the first observation for the game as the second observation, allowing predictions to only have to be made on a single observation of the game. This is not true for most other models. Additionally it prevented models for classification and point estimation from being separate and producing different results. Lastly, because of shiny apps free tier limitations, reading in multiple complex models along with large datasets was causing too much memory to be used and the site to crash. By using simple models which I turned into functions after pulling out the coefficients, I was able to stay within the bounds for shiny apps free tier.</p>
<p>One main problem was still vexing the predictions though, early season games in which teams had played very few or no games. Rather than adding more confounding variables such as the teams points per game last year (which would also become relatively insignificant as the season went on) to the model, I decided to attempt to weight the associated predictors from the previous year, the current year, and league averages together in a single predictor. The idea is that these weighted predictors value previous years success and league averages more at the start of the season and then value current year performance more as the season goes on. This variable mixing tuning process was done with a grid of 99 different starting weight combinations rates of decay. The best weights for the score model and the classification model can be seen below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Best Weights for Score Model</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 4%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">past_success</th>
<th style="text-align: right;">league_avg</th>
<th style="text-align: right;">c</th>
<th style="text-align: right;">rank_rmse</th>
<th style="text-align: right;">rank_rsq</th>
<th style="text-align: right;">rank_mae</th>
<th style="text-align: right;">rank_mape</th>
<th style="text-align: right;">rank_mean</th>
<th style="text-align: right;">rank_max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3.25</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5.25</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6.25</td>
<td style="text-align: right;">11</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Best Weights for Classification Model</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 4%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">past_success</th>
<th style="text-align: right;">league_avg</th>
<th style="text-align: right;">c</th>
<th style="text-align: right;">rank_brier</th>
<th style="text-align: right;">rank_accuracy</th>
<th style="text-align: right;">rank_mn_log_loss</th>
<th style="text-align: right;">rank_mean</th>
<th style="text-align: right;">rank_max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.333333</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.666667</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4.333333</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5.333333</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">7.000000</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7.333333</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Based on this the best overall weights were decided to be as follows:<br>
- Starting Previous Year Weight: 0.8<br>
- Starting League Average Weight: 0.2<br>
- Constant for Decay as Game Number Increases: 0.8</p>
<p>The final models were then fit on the training data and used to make predictions on the testing data. The final models were saved to <code>Models/lm_reg.rds</code>, <code>Models/lm_opp_reg.rds</code>, and <code>Models/class_glm_mod.rds</code>.</p>
<ol start="6" type="1">
<li><strong>Evaluate the models</strong>: The models were evaluated using the <code>yardstick</code> package. The final regression model was evaluated using RMSE, MAE, and R-squared. The final classification model was evaluated using Brier score, log loss, and accuracy. The results of the evaluation can be seen below were saved to <code>Data/lm_reg_metrics.rds</code> and <code>Data/class_glm_metrics.rds</code> and can be seen below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Final Regression Model Test Values</caption>
<thead>
<tr class="header">
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">R2</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">MAPE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10.51046</td>
<td style="text-align: right;">0.5253771</td>
<td style="text-align: right;">8.263366</td>
<td style="text-align: right;">23.36082</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Final Classification Model Test Values</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Brier</th>
<th style="text-align: right;">Log_Loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7960607</td>
<td style="text-align: right;">0.1397764</td>
<td style="text-align: right;">0.431017</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Obviously these results were just a little below the goals set for the project. For the linear regression model the RMSE was 10.5 just above the goal of 10, the MAE was 8.3, which is within a point of our goal of 7.5.</p>
<p>The classification model was much more successful in relation to our preset goals. The Brier score was 0.14, just below the goal of 0.15, and the accuracy was 0.796, which with some rounding reaches the goal of 0.80.</p>
<p>With some more careful scrutiny it can be seen the main culprit for our shortcomings resides in early season games, despite our best efforts to minimize the effects of those games. This can be seen effectively in the plots below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots/lm_avg_error_by_game.png" class="img-fluid figure-img" width="1500"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Plots/classification_accuracy_by_game.png" class="img-fluid figure-img" width="1500"></p>
</figure>
</div>
</div>
</div>
<p>Obviously, it would’ve been ideal to reach all of our prediction goals, but nevertheless the models are still quite useful, particularly as the season progresses.</p>
<ol start="7" type="1">
<li><strong>Interpretation of Coefficients and Variables</strong>: For the linear score model we saw the results below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Regression Model Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-22.9322655</td>
<td style="text-align: right;">2.3688839</td>
<td style="text-align: right;">-9.680620</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">h_a_n</td>
<td style="text-align: right;">0.9900368</td>
<td style="text-align: right;">0.0436613</td>
<td style="text-align: right;">22.675370</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rpi</td>
<td style="text-align: right;">10.2032053</td>
<td style="text-align: right;">1.3121278</td>
<td style="text-align: right;">7.776076</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">rpi_opp</td>
<td style="text-align: right;">-6.9641430</td>
<td style="text-align: right;">1.3121278</td>
<td style="text-align: right;">-5.307519</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">crpi</td>
<td style="text-align: right;">13.7433800</td>
<td style="text-align: right;">0.3467683</td>
<td style="text-align: right;">39.632743</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">crpi_opp</td>
<td style="text-align: right;">-13.5420228</td>
<td style="text-align: right;">0.3467683</td>
<td style="text-align: right;">-39.052075</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ppg</td>
<td style="text-align: right;">0.9053230</td>
<td style="text-align: right;">0.0174468</td>
<td style="text-align: right;">51.890439</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">papg_opp</td>
<td style="text-align: right;">-0.2275360</td>
<td style="text-align: right;">0.0142113</td>
<td style="text-align: right;">-16.010935</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o_rate</td>
<td style="text-align: right;">-0.2050882</td>
<td style="text-align: right;">0.0260241</td>
<td style="text-align: right;">-7.880713</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_rate_opp</td>
<td style="text-align: right;">-0.5769253</td>
<td style="text-align: right;">0.0230855</td>
<td style="text-align: right;">-24.990827</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DWE_opp</td>
<td style="text-align: right;">-0.0600920</td>
<td style="text-align: right;">0.0354056</td>
<td style="text-align: right;">-1.697247</td>
<td style="text-align: right;">0.0896534</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_pace</td>
<td style="text-align: right;">-0.9079990</td>
<td style="text-align: right;">0.0572331</td>
<td style="text-align: right;">-15.864940</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg_pace_opp</td>
<td style="text-align: right;">1.3864090</td>
<td style="text-align: right;">0.0572331</td>
<td style="text-align: right;">24.223920</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">OWE_opp</td>
<td style="text-align: right;">-0.1298628</td>
<td style="text-align: right;">0.0422255</td>
<td style="text-align: right;">-3.075461</td>
<td style="text-align: right;">0.0021024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">papg</td>
<td style="text-align: right;">0.5190537</td>
<td style="text-align: right;">0.0142113</td>
<td style="text-align: right;">36.524043</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">OWE</td>
<td style="text-align: right;">0.4185079</td>
<td style="text-align: right;">0.0422255</td>
<td style="text-align: right;">9.911263</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ppg_opp</td>
<td style="text-align: right;">-0.3407417</td>
<td style="text-align: right;">0.0174468</td>
<td style="text-align: right;">-19.530306</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">DWE</td>
<td style="text-align: right;">-0.1192183</td>
<td style="text-align: right;">0.0354056</td>
<td style="text-align: right;">-3.367217</td>
<td style="text-align: right;">0.0007596</td>
</tr>
<tr class="odd">
<td style="text-align: left;">d_rate</td>
<td style="text-align: right;">0.2452566</td>
<td style="text-align: right;">0.0230855</td>
<td style="text-align: right;">10.623844</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">o_rate_opp</td>
<td style="text-align: right;">0.1877156</td>
<td style="text-align: right;">0.0260241</td>
<td style="text-align: right;">7.213153</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With the amount of data available it is not surprising to find significance for variables. All of the variables are significant except <code>DWE_opp</code>. This is not too surprising because of its strong correlation with <code>d_rate_opp</code> and <code>papg_opp</code>. However, it was left in the model for symmetry with the model predicting the opponent’s score (since <code>DWE</code> and <code>DWE_opp</code> are mirror images of each other). The opponent’s score model is largely the same as the score model, but with the coefficients flipped.</p>
<p>The coefficients for the data are relatively easy to interpret. For example, for each increase of 1 prior point per game for the team, their score is expected to increase by .9 points, holding all other variables constant. Or if a team goes from away to home (a two unit increase) then they are expected to score 1.98 points more, holding all other variables constant.</p>
<p>Notice though the inability to interpret the coefficient of the intercept which is -22.93. Obviously, a team cannot score a negative amount of points. However it is not possible for all predictors to be zero, so the the intercept is not interpretable in this context. Take for example the variable <code>rpi</code> which has the formula <span class="math display">\[RPI = \text{Team win} \% * 0.25 +
\text{Opp. win} \% * 0.5 +
\text{Opp. opp. win} \% * 0.25\]</span> It is not possible for an opponent and the opponent’s opponent to both have a winning percentage of 0 because one of them has to have won the game between them.</p>
<p>There are some other coefficients that are confusing at first glance, such as the -.23 for Prior PTS Allowed Per Game by the opponent. It would be logical that as the opponent allows more points per game, the team would score more points, but that is the opposite of what the coefficient says. This negative coefficient is due to the multicolinearity between the scoring based predictors.</p>
<p>For the classification model we saw the results below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Classification Model Coefficients and Odds Ratios</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">odds_ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.0005051</td>
<td style="text-align: right;">0.6490006</td>
<td style="text-align: right;">-0.0007783</td>
<td style="text-align: right;">0.9993790</td>
<td style="text-align: right;">0.9994950</td>
</tr>
<tr class="even">
<td style="text-align: left;">h_a_n</td>
<td style="text-align: right;">0.2446058</td>
<td style="text-align: right;">0.0113859</td>
<td style="text-align: right;">21.4831601</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.2771178</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ppg</td>
<td style="text-align: right;">0.1303700</td>
<td style="text-align: right;">0.0046707</td>
<td style="text-align: right;">27.9122494</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.1392499</td>
</tr>
<tr class="even">
<td style="text-align: left;">papg</td>
<td style="text-align: right;">0.0794696</td>
<td style="text-align: right;">0.0036955</td>
<td style="text-align: right;">21.5041529</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.0827126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OWE</td>
<td style="text-align: right;">0.0463138</td>
<td style="text-align: right;">0.0120959</td>
<td style="text-align: right;">3.8288728</td>
<td style="text-align: right;">0.0001287</td>
<td style="text-align: right;">1.0474030</td>
</tr>
<tr class="even">
<td style="text-align: left;">DWE</td>
<td style="text-align: right;">0.0059175</td>
<td style="text-align: right;">0.0101208</td>
<td style="text-align: right;">0.5846845</td>
<td style="text-align: right;">0.5587598</td>
<td style="text-align: right;">1.0059350</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rpi</td>
<td style="text-align: right;">2.7417908</td>
<td style="text-align: right;">0.3385382</td>
<td style="text-align: right;">8.0989115</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">15.5147437</td>
</tr>
<tr class="even">
<td style="text-align: left;">crpi</td>
<td style="text-align: right;">3.3514973</td>
<td style="text-align: right;">0.0902198</td>
<td style="text-align: right;">37.1481431</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">28.5454425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o_rate</td>
<td style="text-align: right;">-0.0271013</td>
<td style="text-align: right;">0.0074842</td>
<td style="text-align: right;">-3.6211542</td>
<td style="text-align: right;">0.0002933</td>
<td style="text-align: right;">0.9732626</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_rate</td>
<td style="text-align: right;">0.1007637</td>
<td style="text-align: right;">0.0064466</td>
<td style="text-align: right;">15.6304937</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.1060153</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ppg_opp</td>
<td style="text-align: right;">-0.1303736</td>
<td style="text-align: right;">0.0046707</td>
<td style="text-align: right;">-27.9130941</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.8777674</td>
</tr>
<tr class="even">
<td style="text-align: left;">papg_opp</td>
<td style="text-align: right;">-0.0794365</td>
<td style="text-align: right;">0.0036955</td>
<td style="text-align: right;">-21.4952769</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.9236366</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OWE_opp</td>
<td style="text-align: right;">-0.0463049</td>
<td style="text-align: right;">0.0120959</td>
<td style="text-align: right;">-3.8281433</td>
<td style="text-align: right;">0.0001291</td>
<td style="text-align: right;">0.9547508</td>
</tr>
<tr class="even">
<td style="text-align: left;">DWE_opp</td>
<td style="text-align: right;">-0.0059270</td>
<td style="text-align: right;">0.0101206</td>
<td style="text-align: right;">-0.5856353</td>
<td style="text-align: right;">0.5581207</td>
<td style="text-align: right;">0.9940906</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rpi_opp</td>
<td style="text-align: right;">-2.7413040</td>
<td style="text-align: right;">0.3385378</td>
<td style="text-align: right;">-8.0974839</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0644862</td>
</tr>
<tr class="even">
<td style="text-align: left;">crpi_opp</td>
<td style="text-align: right;">-3.3519798</td>
<td style="text-align: right;">0.0902203</td>
<td style="text-align: right;">-37.1532957</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0350150</td>
</tr>
<tr class="odd">
<td style="text-align: left;">o_rate_opp</td>
<td style="text-align: right;">0.0270887</td>
<td style="text-align: right;">0.0074841</td>
<td style="text-align: right;">3.6194827</td>
<td style="text-align: right;">0.0002952</td>
<td style="text-align: right;">1.0274590</td>
</tr>
<tr class="even">
<td style="text-align: left;">d_rate_opp</td>
<td style="text-align: right;">-0.1007383</td>
<td style="text-align: right;">0.0064465</td>
<td style="text-align: right;">-15.6268284</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.9041696</td>
</tr>
<tr class="odd">
<td style="text-align: left;">avg_pace</td>
<td style="text-align: right;">-0.2555660</td>
<td style="text-align: right;">0.0156980</td>
<td style="text-align: right;">-16.2801995</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.7744780</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_pace_opp</td>
<td style="text-align: right;">0.2555479</td>
<td style="text-align: right;">0.0156979</td>
<td style="text-align: right;">16.2790646</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.2911688</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>All of variables are significant except <code>DWE</code> and <code>DWE_opp</code> (and the intercept). This is not too surprising since those variables mirror each other. However, they were left in the model for symmetry and for consistency with the score model.</p>
<p>There are some very nice interpretations that can be made from the coefficients of the classification model. From the estimate we can acquire the odds ratio, which tells us how much more likely a team is to win given a one unit increase in the predictor while holding the other variables constant. For example, a teams odds of winning are 14% greater for each increase in one prior point per game for the team. Another easy interpretation is the effect of location. Since location is a ternary variable (away, neutral, home) we can see that a teams odds of winning are 63% greater when playing at home compared to playing away.</p>
<p>Notice the the very large odds ratios for the variables <code>crpi</code> and <code>rpi</code>. This is due to the scale of those variables, which is between 0 and 1. For <code>crpi</code>, a measure of a teams true class level, a one unit increase in <code>crpi</code> would make a team with a <code>cpri = 1</code> 28.5 times more likely to win than a team with <code>crpi = 0</code>. This is extrapolation though. If we want a more realistic interpretation, we can do some quick math. A median <code>crpi</code> for a class 1 team is approximately .21 and the median <code>crpi</code> for a class 5 team is approximately .91. By using the estimated odds ratio of <span class="math inline">\(28.5^{.7}\)</span> we can see that a class 6 team would be 10.4 times more likely to win than a class 1 team, holding all other variables constant.</p>
<ol start="8" type="1">
<li><strong>Make predictions</strong>: Predictions with the selected models were capable of being made on any new data in the modeling data form. The ranking process for the teams is actually based on this. A grid is made with all the possible matchups for the teams in a class. Then each game is predicted. The percentage of games that they would be expected to win is calculated and that is used to rank the teams. Daily predictions are also made for each day’s games and displayed in the shiny app. The <code>sim_single_game()</code> function is used to make both the matchup data and the prediction for any game between any two teams.</li>
</ol>
<p>Additionally since the original data only included games played before January 28, 2025, the rest of the 2025 season data can be used as almost a secondary test set to evaluate the model. From Jamuary 28, 2025 to March 8, 2025 there were 2,709 games played and the classification model had an accuracy of 82.8%. The score model had a mean absolute error of 7.69 points for the 5,418 predictions made. This is encouraging and shows that the model is still performing well on new data.</p>
<ol start="9" type="1">
<li><p><strong>Create a Shiny app</strong>: A Shiny app was created to allow users to interact with the model and make predictions. The app is available at <a href="https://jtlieb.shinyapps.io/mshsaa_girls_rankings/">Lieb MSHSAA Girls Rankings</a>. It includes daily rankings for each class, predictions on the upcoming games, the ability to simulate a single game between two teams of your choosing, and page where you can see a breakdown of games for a single team.</p></li>
<li><p><strong>Make the Process Automated</strong>: The scraping, cleaning, modeling data creation, and prediction processes were all automated. The <code>daily_work.R</code> file and the <code>deploy_app.R</code> file are both run each day by the task scheduler to update the data in each of the data sets for the app and then to redeploy the app with the updated data.</p></li>
</ol>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<section id="goals-assessment" class="level4">
<h4 class="anchored" data-anchor-id="goals-assessment">Goals Assessment</h4>
<p>The goals for the project were largely met and the initial questions were answered sufficiently.</p>
<ol type="1">
<li><p>Yes the data for a single high school sport in a single state can and was accumulated into a single usable and accessible dataset. This is much easier said than done though as the data was extremely error laden and took a significant amount of time to parse through and determine what is accurate and what is not. Even after creating a relatively robust system it is still possible to have errors in the data or for certain real games to be lost. For example if team A played team B and won 63-50 and then team A played team B again two days later and won 63-51, that second game would be lost through the cleaning workflow due to the plethora of games that were entered with slightly different scores for the same game, but within a 3 day span, when in actuality the teams only played each other once (but entered different scores separately to MSHSAA).</p></li>
<li><p>Yes, we can predict outcomes, both scores and win probabilities, of every single game played with a data driven model that is accurate enough to be useful. This is evidenced by accuracy rates of the model hovering around 80% and a mean absolute error of around 8 points per projection. These are not perfect, but provide a fantastic baseline for expectations.</p></li>
<li><p>Yes, we can rank every team in the state, rather than just the top 10 with analytics rather than opinion. By predicting the outcome of every game, we can rank teams based on their expected win percentage against other teams in their class. This is a much more robust and data driven way to rank teams than simply relying on coaches polls or subjective opinions. There is now a way to tell who is the 25th ranked team or the worst team in a class, rather than just the top 10.</p></li>
<li><p>Yes, we can determine what factors are most important in determining the outcome of a high school game. The coefficients from the models provide insight into what information the variables tell us about the outcome of a game.</p></li>
<li><p>Yes, this information can be processed and presented in a way that is easily accessible and interpretable to the public, while being adaptable to new data. The Shiny app provides a user friendly interface for users to interact with the model and make predictions. The app is also adaptable to new data, as it is updated daily with new games and predictions.</p></li>
</ol>
</section>
</section>
<section id="practical-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="practical-recommendations">Practical Recommendations</h2>
<ol type="1">
<li>Take the model for what it is: An approximation of what is likely to happen based on past data. Many things outside of the model can affect the outcome of a game, such as injuries, sickness, transfer students, eligibility, size matchups, etc. The model is simple score and school data and does not account for these factors.</li>
</ol>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<ol type="1">
<li><p><strong>Dirty Data</strong>: The data is not perfect and there are still errors in the data. This is a limitation of the data itself and the scraping process. While we have done our best to clean the data, there may still be errors that affect the predictions.</p></li>
<li><p><strong>Limited Data</strong>: The data is limited at the beginning of the season because all we have access to is data related to scores. If information were available on individual players, roster turnover, coaching changes, etc. this could be used to improve the early season predictions. Additionally, the data is limited to a single state and a single sport, which may not be generalizable to other states or sports.</p></li>
<li><p><strong>Model Limitations</strong>: The models are simple linear models. This neglects any potential interactions. Logically, the home advantage a team has in the round of 16 in the state tournament is likely greater than the home advantage a team has in a regular season game in December, but the model would fail to capture this. There are several other examples that could be readily identified similarly.</p></li>
<li><p><strong>Shiny App Limitations</strong>: The Shiny app is limited by the free tier of shinyapps.io. This means that there are limitations on the amount of data that can be loaded, the amount of memory that can be used, and the amount of time people can use the app. This limited my modeling heavily because I had to use simple models and functions rather than loading in large complex models.</p></li>
</ol>
</section>
<section id="changes-for-future-work" class="level2">
<h2 class="anchored" data-anchor-id="changes-for-future-work">Changes for Future Work</h2>
<ol type="1">
<li><p><strong>Reduce Multicollinearity</strong>: The models could be improved by reducing multicollinearity between predictors. This could be done by removing some of the highly correlated predictors or by using regularization techniques such as ridge regression or lasso regression. These were tampered with in the modeling process, but ultimately rejected because the simple models were performing well enough. The main issue with multicollinearity is the interpretation of coefficients, which is confounded by the presence of other variables. Principal component analysis could also be used to reduce the dimensionality of the data and remove multicollinearity.</p></li>
<li><p><strong>Capture Interactions More</strong>: The models could be improved by capturing interactions between predictors. This could be done by adding interaction terms to the models or by using more complex models such as decision trees or random forests. These were also tampered with in the modeling process, but ultimately rejected because the simple models were performing well enough and due to memory constraints. Most interactions were not significant when fitting models, but logically some exist.</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>